unit u_barang_test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Windows, DBAccess, cxGridLevel, cxCheckBox, DB, Buttons, cxDataStorage,
  Messages, cxClasses, cxControls, dxSkinsCore, cxEdit, Dialogs, sButton, Controls,
  cxGridCustomTableView, cxSpinEdit, sPanel, MemDS, Classes, Forms, sEdit,
  cxLookAndFeels, cxGridTableView, sSpeedButton, sSkinProvider, cxCustomData, cxDBData,
  cxGridDBTableView, cxGridCustomView, cxFilter, dxSkinscxPCPainter, cxData, cxGrid,
  ExtCtrls, StdCtrls, SysUtils, cxGridCustomPopupMenu, u_barang, MyAccess, ComCtrls,
  cxTextEdit, cxNavigator, cxLookAndFeelPainters, dxSkinsDefaultPainters, Graphics,
  cxStyles, Variants, cxGraphics;

type
  // Test methods for class TF_barang

  TestTF_barang = class(TTestCase)
  strict private
    FF_barang: TF_barang;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestFormShow;
  end;

implementation

procedure TestTF_barang.SetUp;
begin
//  FF_barang := TF_barang.Create(nil);
end;

procedure TestTF_barang.TearDown;
begin
//  FF_barang.Free;
//  FF_barang := nil;
end;

procedure TestTF_barang.TestFormShow;
begin
  Check(True, 'salah');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTF_barang.Suite);
end.

